### PR TITLE
Adding an RCA for Cluster events resulting in a Node going down

### PR DESCRIPTION
**Pull request by sidhant012**
image

### CODE REVIEW

**Comment by jeffj6123** [comment]
@sidhant012  change the target branch to master

**Comment by sidhant012** [comment]
> @sidhant012 change the target branch to master

It doesn't look like master is currently up to date with eventstore-analysis at the moment. There are some past changes that still need to be merged into master

**Comment by sidhant012** [comment]
So if this looks good to you I can merge this and then merge of all of eventstore-analysis into master at once?

**Comment by jeffj6123** [comment]
@sidhant012  that works

**Pull request merged**
